### ISSUE TITLE
Error with "yarn add"

### ISSUE THREAD

**Issue by zsjanko** [wwimmo/react-native-sketch-image#33]
Hi,

I wanted to run the ios app in the example folder. According to the readme file, first I tried to install in the example folder with the following command: yarn add https://github.com/wwimmo/react-native-sketch-canvas.git

However, it produced a number of errors. The output is this: [out.txt](https://github.com/wwimmo/react-native-sketch-image/files/5219102/out.txt). It seems that there are problems with installing fsevents, and some others. How can I go further, install the package with yarn and compile the example with xcode? I am on macOS Catalina 10.15.6, node version 12.18.3 and yarn version 1.22.5.

Thanks,
Zsolt

**Comment by creambyemute** [comment]
@zsjanko Hmm, I haven't run the example for quite a time. Could be that it its erroring out.

Are you looking at this library for the shapes? Because it's mostly discontinued due to various problems. If you can live without the shapes and are fine with drawing on a background or an image, have a look at https://github.com/creambyemute/react-native-sketch-canvas which is the original repo with two iOS fixes.

**Comment by zsjanko** [comment]
Thank you
